export enum BookIconEnum {
  moon = "moon",
  star = "star",
  flower = "flower",
  clover = "clover",
  plant = "plant",
  loveheart = "loveheart",
  cherry = "cherry",
  feather = "feather",
  cloud = "cloud",
  spade = "spade",
  diamond = "diamond",
  club = "club",
  heart = "heart",
  crown = "crown",
  fire = "fire",
  bluefire = "bluefire",
  leaf = "leaf",
  paint = "paint",
  coffee = "coffee",
  bird = "bird",
  masks = "masks",
  wand = "wand",
  orb = "orb",
}
